apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-backend
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-backend
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0