apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
  namespace: adex-stage
  labels:
    app: java-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      containers:
      - name: java-backend
        image: harbor.adexassesment.com/adex-assesment-stage/java-backend:STAGE.3
        ports:
          - containerPort: 8080  
        env:
            - name: MONGODBHOSTNAME
              valueFrom:
                secretKeyRef:
                  name: java-secret
                  key: MONGODBHOSTNAME
            - name: MONGODBPORT
              valueFrom:
                secretKeyRef:
                  name: java-secret
                  key: MONGODBPORT
            - name: MONGODBNAME
              valueFrom:
                secretKeyRef:
                  name: java-secret
                  key: MONGODBNAME
            - name: MONGOURI
              valueFrom:
                secretKeyRef:
                  name: java-secret
                  key: MONGOURI
            - name: MONGOUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGOPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
        resources:
            limits:
              cpu: "800m"
              memory: "256Mi" 
            requests:
              cpu: "800m"
              memory: "128Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  revisionHistoryLimit: 5