apiVersion: v1
kind: Secret
metadata:
  name: java-secret
  namespace: adex-stage
type: Opaque
data:
  MONGODBHOSTNAME: bW9uZ29kYi1zZXJ2aWNl
  MONGODBNAME: dGVzdF9kYg==
  MONGODBPORT: MjcwMTc=
  MONGOURI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy90ZXN0X2Ri