apiVersion: v1
kind: Service
metadata:
  name: java-backend-service
  namespace: adex-dev
spec:
  selector:
    app: java-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080  
      targetPort: 8080 
  type: ClusterIP
