apiVersion: v1
kind: Service
metadata:
  name: nodejs-frontend-service
  namespace: adex-dev
spec:
  type: ClusterIP
  selector:
    app: nodejs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000