apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
  namespace: adex-dev
  labels:
    app: java-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      containers:
      - name: java-backend
        image: harbor.adexassesment.com/adex-assesment-dev/java-backend:DEV.5
        ports:
          - containerPort: 8080  
        env:
            - name: MONGODBHOSTNAME
              valueFrom:
                secretKeyRef:
                  name: java-secret
                  key: MONGODBHOSTNAME
            - name: MONGODBPORT
              valueFrom:
                secretKeyRef:
                  name: java-secret
                  key: MONGODBPORT
            - name: MONGODBNAME
              valueFrom:
                secretKeyRef:
                  name: java-secret
                  key: MONGODBNAME
            - name: MONGOURI
              valueFrom:
                secretKeyRef:
                  name: java-secret
                  key: MONGOURI
            - name: MONGOUSERNAME
              valueFrom:
                secretKeyRef:
                  name: dev-mongodb-secret
                  key: mongo-root-username
            - name: MONGOPASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-mongodb-secret
                  key: mongo-root-password
        resources:
            limits:
              cpu: "500m"
              memory: "256Mi" 
            requests:
              cpu: "500m"
              memory: "128Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Secret
metadata:
  name: java-secret
  namespace: adex-dev
type: Opaque
data:
  MONGODBHOSTNAME: bW9uZ29kYi1zZXJ2aWNl
  MONGODBNAME: dGVzdF9kYg==
  MONGODBPORT: MjcwMTc=
  MONGOURI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy90ZXN0X2Ri
---
apiVersion: v1
kind: Service
metadata:
  name: java-backend-service
  namespace: adex-dev
spec:
  selector:
    app: java-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080  
      targetPort: 8080 
  type: ClusterIP
