apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: adex-stage
spec:
  encryptedData:
    mongo-root-password: AgCMzz8MswPuYsZV7lgUckKCUyoAr9cMXVfvcCVvcOWlfuAUKTiPDDz1o5lhAwF7eNI6t2CGFawgySKiNVLx3n2L9xvVHXn6o/SIEcojZk2deqnmnHQq4l08M3fEstJiYB+VqD8L1e2ZMRodXLI1yqZ9PWj305qLayuvnnlgCp5C2ScKZsWp3mNj4kMERSGQRJMeA81/V0DkRYCFs9f9fZcrvk2rHl2yGIswrrjhWFirNKBkuqpUuYUGi77GNVEw7DPD1haVuFGsQu1nDyPf/DS4CJJfzUMtCBuKLfsBeTrDfPkjBjBTru3H2xK190tLzegHITgYnd2NqyzCTmMDfU8MCu3xkDLqSHxgFpItlaUzkApyNQqH2Fjz2z3NX6Whx0DL2tdU9USOfzKTaOjkS3gULIp8IqXYimDMQcQLUD6zRkwdtY1weqJRPYxcGf1VpJZUR2y3EKiwFOAzM9TswhufZ/XksfNA/mOcoHfApo+CEgbA1USuPgGW1Y3oWyDi+Yle2svHl6mp7JUHPZ3oPAwWCuS0g0jyAI1juDmqswvyx0vtxE5JK9QwodXiMnoTyg+ki4S3/zsb3gGBt/LBG8dv2HfxWH5k03LwDc9Sj4V3oexOsneErlfZngXGwhd7Ddpt5IllODOF+h6EZBGn1Gx7oGV/9Km3ViWAmXT9c/DvhMS9SmgGNanslwk43M02aXCCB4wlrn+Ukg==
    mongo-root-username: AgCZrkck3CLAWP0p02BhWTUy89BvA7Qlft2lSFm5/lUVqD1+1g9SbZQX8bdWo/AjMOfDvh7vhovWrmnqA2CdI3vS/9PAxW6GhXK7dq+9vq7PrDUzqjH/JwZqJPHCVlKt30+qL+clIB3Ziw7Xq6Ug7TjgNoHfr7Qgs1OkN50vHiXtb/o3zaP8T+iq4x1LnI9MpXvylU5i//Muy969vF125bWT/Frp+C0ViSHpM8jNr6KCzV9ex/nb8gQiK3qxTU53u9jpzQV2JDNwV5srJqyuKN1mgWw4+pdG1vetUkUnX11Rjdxc7DhKSdSOWPIouQPfnhYnfirhdUGz3JKDf4jIVMMsXbnULhXH5hX0XxaRu+NhU/r6Q5uCAGXRMRZdcilwpuy52a9+tYy6QL82JbP24N4sKrjvAsK+LA5bKPVdSVCDOiyOWIhRavWSWQpisM6woRuqmicLAzPE7n1w8vVwFs3FvtfHhUzoKJgTlKgz4xxYWdlKNT1eBGIx5NQkgDcr+/EP8nUo6UdBJDgEkPOBD+v/i8AJuH/mEVhN4k3kVDGU7Zr/W+BoEAvEIt7STSUo/+l3LXXyNkNRD1YQOu21NzuqdeUfTZB9mSDQ8hPQJPPI9BtPBot3GdmNANH/1dhC6zsU6sAWYGQZQasOQIVVrYHJcBcWVBhSrCaOYNOLElLTNzTBDMx9dsb85pjTidejSoAuIAtpyg==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: adex-stage
    type: Opaque